FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /app

COPY ./GpgDecryptionApp.sln .
COPY ./GpgDecryptionApp.Tests/GpgDecryptionApp.Tests.csproj ./GpgDecryptionApp.Tests/
COPY ./GpgDecryptionApp/GpgDecryptionApp.csproj ./GpgDecryptionApp/

RUN dotnet restore

COPY . .
RUN dotnet build

FROM build AS test
WORKDIR /app/GpgDecryptionApp.Tests

RUN dotnet test -l "console;verbosity=normal" --list-tests
